# Generated by Django 2.2 on 2019-04-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdashboardmodule',
            name='user',
            field=models.CharField(max_length=255, verbose_name='user'),
        ),
    ]
