language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
env:
  - DJANGO=1.6.11
  - DJANGO=1.7.7
  - DJANGO=1.8.3
  - DJANGO=1.9.8
before_install:
  - export DJANGO_SETTINGS_MODULE=jet.tests.settings
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install . --use-mirrors
  - pip install coverage==3.7.1
  - pip install coveralls==0.5
script:
  - coverage run --source=jet --omit=*/migrations/*,*/south_migrations/*,*/tests/* manage.py test jet
after_success:
  - coverage report
  - coveralls
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=1.7.7
    - python: 2.6
      env: DJANGO=1.8.3
    - python: 2.6
      env: DJANGO=1.9.8
    - python: 3.2
      env: DJANGO=1.9.8
    - python: 3.3
      env: DJANGO=1.9.8
