language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
env:
  - DJANGO="<1.7"
  - DJANGO="<1.8"
  - DJANGO="<1.9"
  - DJANGO="<1.10"
  - DJANGO="<1.11"
  - DJANGO="<1.12"
  - DJANGO="<2.1"
before_install:
  - export DJANGO_SETTINGS_MODULE=jet.tests.settings
install:
  - pip install -q "Django${DJANGO}"
  - pip install .
  - pip install coverage==3.7.1
  - pip install coveralls==0.5
script:
  - coverage run --source=jet --omit=*/migrations/*,*/south_migrations/*,*/tests/* manage.py test jet
after_success:
  - coverage report
  - coveralls
matrix:
  exclude:
    - python: 2.6
      env: DJANGO="<1.8"
    - python: 2.6
      env: DJANGO="<1.9"
    - python: 2.6
      env: DJANGO="<1.10"
    - python: 2.6
      env: DJANGO="<1.11"
    - python: 2.6
      env: DJANGO="<1.12"
    - python: 2.6
      env: DJANGO="<2.1"

    - python: 2.7
      env: DJANGO="<2.1"

    - python: 3.2
      env: DJANGO="<1.10"
    - python: 3.2
      env: DJANGO="<1.11"
    - python: 3.2
      env: DJANGO="<1.12"
    - python: 3.2
      env: DJANGO="<2.1"

    - python: 3.3
      env: DJANGO="<1.10"
    - python: 3.3
      env: DJANGO="<1.11"
    - python: 3.3
      env: DJANGO="<1.12"
    - python: 3.3
      env: DJANGO="<2.1"

    - python: 3.5
      env: DJANGO="<1.7"
    - python: 3.5
      env: DJANGO="<1.8"
    - python: 3.6
      env: DJANGO="<1.7"
    - python: 3.6
      env: DJANGO="<1.8"

    - python: pypy
      env: DJANGO="<2.1"
